### ISSUE TITLE
no Receive binary data

### ISSUE THREAD

**Issue by fabienjean** [socketio/socket.io-client-cpp#304] opened 2021-05-14 09:54 UTC
Hi,

When en send binary buffer from js server :
var buf = new Buffer.alloc(3);
buf.writeUInt8(1, 0, 1);
socket.to(room).emit(buf);
I do not receive the data on the server side.

Do you help me ?
Thanks a lot

**Comment by linsinan1995** [comment] 2021-06-17 20:33
Can the patch in issue #299 solve your issue?

**Comment by jmigual** [comment] 2022-03-10 13:22
Closing as duplicate of #299

**Closed by jmigual** 2022-03-10 13:22 UTC
